### ISSUE TITLE
initial imports have 0 airports, 0 waypoints

### ISSUE THREAD

**Issue by smitty97** [kenz67/FlightSim-FlightPlanManager#6]
initial plan imports have 0 airports, 0 waypoints - if you import the same file again, the counts are correct

**Comment by kenz67** [comment]
Thanks, will take a look

**Comment by kenz67** [comment]
One question, if you import, then exit the program and come back in, are the values filled in then?  It may be a display issue

**Comment by kenz67** [comment]
Hmm, that is very strange, doing my day job now, but will take a look when i get a chance

**Comment by kenz67** [comment]
Sorry for the delay, i am going to try to look at this, got a new PC and spending a lot of time getting it configured but I will get to this once everything is setup

**Comment by kenz67** [comment]
New release today (1.0) should hopefully fix this issue
